import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";
import Head from "next/head";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "interviewprep.AI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
    <head>
    <link rel="alternate icon" href="/favicon.png" />
    </head>
      <body className={inter.className}>
        <Toaster />
        {children}</body>
    </html>
    </ClerkProvider>
  );
}
